### ISSUE TITLE
Windows Setup Not Working

### ISSUE THREAD

**Issue by Nicistarful** [FurryBotCo/E621Downloader#3]
### What was expected to happen
The downloader should install when executing the "E621Downloader.Setup.exe" file.

### What actually happened
A splash screen with an animation showed, the taskbar loading bar indicated progress and then the splash screen closed and nothing else happened.

### Steps to reproduce
Install it on Windows by executing the Setup.exe.

### Extra information
OS: Windows 10
Version: v1.0.0-beta.8
Downloaded file: E621Downloader.Setup.exe
Executed as Admin: Yes

**Comment by DonovanDMC** [comment]
Have you looked in the start menu (Windows Icon bit) and seen if it's there? Squirrel.Windows does funky things when installing

**Comment by Nicistarful** [comment]
It didn't appear in the Start Menu :/ 
Seems like it didn't even install at all.

**Comment by DonovanDMC** [comment]
Open `%localappdata%\e621downloader` if it exists, and see if it put anything in there. I'm working on switching up stuff right now, and don't have easy access to a Windows installation anymore, so I can't help much right now.

**Comment by Nicistarful** [comment]
I'll check if the folder exists the next time I'm back home.

**Comment by DonovanDMC** [comment]
Gonna work on this today and see what I can figure out

**Comment by DonovanDMC** [comment]
I've managed to find an executable at `%userprofile%\AppData\Local\E621Downloader\E621Downloader.exe`. Try running that in the run menu (windows key + r)
Not seeing a start menu entry, or a desktop icon. I feel like I removed the code for this at some point. I'm going to go back and see what I can do to fix that, but you should be able to launch the application by running that. (make sure to uninstall and install the latest version)

**Comment by DonovanDMC** [comment]
I'm pretty sure I know how to fix it, but it's 6am and by brain is fried, so I'll do this later. ~~But I should have a fixed version before the day's over.~~

I'm working on adding more in before I push the update out, so it's going to take bit longer.

**Comment by DonovanDMC** [comment]
Release `v1.0.0-beta.11` will have a fix for this in it.
